/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ub.info.prog2.DeCaraltOscarSeguraPau.vista;

import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import prog2.controlador.Controlador;

/**
 *
 * @author Pau Segura
 */
public class AppMercatUB extends javax.swing.JFrame {

    Controlador controlador;

    /**
     * Creates new form AppMercatUB
     *
     */
    public AppMercatUB() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.controlador = new Controlador();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtMercat = new javax.swing.JLabel();
        btnGestioClients = new javax.swing.JButton();
        btnGestioArticles = new javax.swing.JButton();
        btnGestioComandes = new javax.swing.JButton();
        btnRecuperar = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GESTIÓ MERCATUB");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMercat.setBackground(new java.awt.Color(0, 0, 0));
        txtMercat.setFont(new java.awt.Font("Dialog", 1, 76)); // NOI18N
        txtMercat.setForeground(new java.awt.Color(255, 255, 255));
        txtMercat.setText(" MERCAT UB");
        jPanel1.add(txtMercat, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, -1, 80));

        btnGestioClients.setBackground(new java.awt.Color(255, 255, 255));
        btnGestioClients.setForeground(new java.awt.Color(0, 0, 0));
        btnGestioClients.setText("Gestió Clients");
        btnGestioClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestioClientsActionPerformed(evt);
            }
        });
        jPanel1.add(btnGestioClients, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 130, -1));

        btnGestioArticles.setBackground(new java.awt.Color(255, 255, 255));
        btnGestioArticles.setForeground(new java.awt.Color(0, 0, 0));
        btnGestioArticles.setText("Gestió Articles");
        btnGestioArticles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestioArticlesActionPerformed(evt);
            }
        });
        jPanel1.add(btnGestioArticles, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 130, -1));

        btnGestioComandes.setBackground(new java.awt.Color(255, 255, 255));
        btnGestioComandes.setForeground(new java.awt.Color(0, 0, 0));
        btnGestioComandes.setText("Gestió Comandes");
        btnGestioComandes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestioComandesActionPerformed(evt);
            }
        });
        jPanel1.add(btnGestioComandes, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        btnRecuperar.setBackground(new java.awt.Color(255, 255, 255));
        btnRecuperar.setForeground(new java.awt.Color(0, 0, 0));
        btnRecuperar.setText("Recuperar dades");
        btnRecuperar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecuperarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRecuperar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 130, -1));

        btnGravar.setBackground(new java.awt.Color(255, 255, 255));
        btnGravar.setForeground(new java.awt.Color(0, 0, 0));
        btnGravar.setText("Gravar dades");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGravar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 130, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/latest.png"))); // NOI18N
        jLabel1.setText("ONLY");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Mètode per a donar funcionalitat al button Gestió clients
     *
     * @param evt Permet assignar un event
     */
    private void btnGestioClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestioClientsActionPerformed
        // TODO add your handling code here:
        FrmGestioClients clients = new FrmGestioClients(controlador);
        clients.setVisible(true);


    }//GEN-LAST:event_btnGestioClientsActionPerformed
    /**
     * Mètode per a donar funcionalitat al button Gestió articles
     *
     * @param evt Permet assignar un event
     */
    private void btnGestioArticlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestioArticlesActionPerformed
        FrmGestioArticles articles = new FrmGestioArticles(controlador);
        articles.setVisible(true);
        

    }//GEN-LAST:event_btnGestioArticlesActionPerformed
    /**
     * Mètode per a donar funcionalitat al button Gestió comandes
     *
     * @param evt Permet assignar un event
     */
    private void btnGestioComandesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestioComandesActionPerformed
        // TODO add your handling code here:
        FrmGestioComandes comandes = new FrmGestioComandes(controlador);

        comandes.setVisible(true);
    }//GEN-LAST:event_btnGestioComandesActionPerformed
    /**
     * Mètode per a donar funcionalitat al button Gravar dades
     *
     * @param evt Permet assignar un event
     */
    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        try {
            // TODO add your handling code here:
            String fitxer = JOptionPane.showInputDialog("Digues el nom del fitxer(amb aquest format ./controlador.dat)");

            controlador.guarda(fitxer);
        } catch (MercatException ex) {

            JOptionPane.showMessageDialog(this, ex.getMessage(), "Mercat exception", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_btnGravarActionPerformed
    /**
     * Mètode per a donar funcionalitat al button Recuperar dades
     *
     * @param evt Permet assignar un event
     */
    private void btnRecuperarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecuperarActionPerformed
        // TODO add your handling code here:
        String fitxer;
        final JFileChooser fc = new JFileChooser();
        int seleccion = fc.showOpenDialog(this);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            try {
                fitxer = fc.getSelectedFile().getName();
                controlador.carregaDades(fitxer);
            } catch (MercatException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Mercat Exception", JOptionPane.ERROR_MESSAGE);
            } 

        }


    }//GEN-LAST:event_btnRecuperarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppMercatUB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppMercatUB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppMercatUB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppMercatUB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppMercatUB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGestioArticles;
    private javax.swing.JButton btnGestioClients;
    private javax.swing.JButton btnGestioComandes;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnRecuperar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtMercat;
    // End of variables declaration//GEN-END:variables
}
