/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ub.info.prog2.DeCaraltOscarSeguraPau.vista;

import java.util.List;
import javax.swing.JList;
import javax.swing.JOptionPane;

import prog2.controlador.Controlador;

/**
 *
 * @author Pau Segura
 */
public class FrmAfegirComandes extends javax.swing.JFrame {

    private final Controlador controlador;
    JList list;

    /**
     * Creates new form FrmAfegirComandes
     * 
     * @param parent Indica el tipus d'awt
     * @param modal Boolean
     * @param controlador Permet accedir als mètodes de la classe controlador
     */
    public FrmAfegirComandes(java.awt.Frame parent, boolean modal, Controlador controlador) {

        initComponents();
        this.controlador = controlador;
        this.setLocationRelativeTo(null);
        omplirModelArticles();
        omplirModelClients();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etClients = new javax.swing.JLabel();
        etArticles = new javax.swing.JLabel();
        btnAcceptarComanda = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        chkComanda = new javax.swing.JCheckBox();
        etUnitats = new javax.swing.JLabel();
        txtUnitats = new javax.swing.JTextField();
        cmbClients = new javax.swing.JComboBox<>();
        cmbArticle = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AFEGIR COMANDES");

        etClients.setText("Client:");

        etArticles.setText("Article:");

        btnAcceptarComanda.setText("Acceptar");
        btnAcceptarComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptarComandaActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        chkComanda.setText("Comanda Premium?");

        etUnitats.setText("Unitats:");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("AFEGEIX UNA COMANDA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(btnAcceptarComanda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                        .addComponent(btnCancelar)
                        .addGap(156, 156, 156))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(etUnitats)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUnitats))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etArticles, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(etClients))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbClients, 0, 654, Short.MAX_VALUE)
                                    .addComponent(cmbArticle, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(0, 65, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(173, 173, 173))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(chkComanda)
                        .addGap(319, 319, 319))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etClients)
                    .addComponent(cmbClients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etArticles)
                    .addComponent(cmbArticle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUnitats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etUnitats))
                .addGap(18, 18, 18)
                .addComponent(chkComanda)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAcceptarComanda)
                    .addComponent(btnCancelar))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 /**
     * Mètode per a donar funcionalitat al button Cancelar
     * @param evt Permet assignar un event
     */
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        FrmGestioComandes comanda = new FrmGestioComandes(controlador);
        comanda.setVisible(true);

    }//GEN-LAST:event_btnCancelarActionPerformed
 /**
     * Mètode per a donar funcionalitat al button Acceptar
     * @param evt Permet assignar un event
     */
    private void btnAcceptarComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptarComandaActionPerformed
        try {
            int quant = Integer.parseInt(txtUnitats.getText());
            controlador.afegirComanda(cmbArticle.getSelectedIndex(), cmbClients.getSelectedIndex(), quant, chkComanda.isSelected());

        } catch (IndexOutOfBoundsException ex) {
            JOptionPane.showMessageDialog(this, "La posició del client i/o de l'article és més gran que la llista","ERROR: INDEX OUT OF BOUNDS", JOptionPane.ERROR_MESSAGE);
        } catch (MercatException ex) {
           JOptionPane.showMessageDialog(this, "La comanda no pot ser urgent si l'article no admet enviament urgent ","ERROR: MERCAT EXCEPTION", JOptionPane.ERROR_MESSAGE);
        }catch (NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Et falta una dada","ERROR: MERCAT EXCEPTION", JOptionPane.ERROR_MESSAGE);
        } finally {
            this.setVisible(false);
            FrmGestioComandes comandes = new FrmGestioComandes(controlador);
            comandes.setVisible(true);
        }


    }//GEN-LAST:event_btnAcceptarComandaActionPerformed
    
    /**
     * Mètode per a omplir l'Array d'Articles que posteriorment voldrem mostrar per pantalla
     * a partir del mètode toString
     */
    private void omplirModelArticles() {

        cmbArticle.removeAllItems();
        //try{

        List<String> s = controlador.recuperaArticles();
        for (String item : s) {
            cmbArticle.addItem(item);

        }

        /*}catch(MercatException e){
        JOptionPane.showMessageDialog(this, e.getMessage(), "warning", JOptionPane.WARNING_MESSAGE);
        
    }*/
    }
    /**
     * Mètode per a omplir l'Array de Clients que posteriorment voldrem mostrar per pantalla
     * a partir del mètode toString
     */

    private void omplirModelClients() {
        cmbClients.removeAllItems();

        List<String> s = controlador.recuperaClients();
        for (String item : s) {
            cmbClients.addItem(item);

        }
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceptarComanda;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JCheckBox chkComanda;
    private javax.swing.JComboBox<String> cmbArticle;
    private javax.swing.JComboBox<String> cmbClients;
    private javax.swing.JLabel etArticles;
    private javax.swing.JLabel etClients;
    private javax.swing.JLabel etUnitats;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtUnitats;
    // End of variables declaration//GEN-END:variables
}
