/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ub.info.prog2.DeCaraltOscarSeguraPau.vista;

import java.util.List;
import javax.swing.DefaultListModel;
import prog2.controlador.*;

/**
 *
 * @author Pau Segura
 */
public class FrmGestioClients extends javax.swing.JFrame {

    private final Controlador controlador;

    /**
     * Creates new form FrmGestioClients
     * @param controlador Permet accedir als mètodes de la classe controlador
     */
    public FrmGestioClients(Controlador controlador) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.controlador = controlador;
        omplirModel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAfegir = new javax.swing.JButton();
        btnTornar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstMostraClients = new javax.swing.JList<>();
        etLlista = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GESTIÓ CLIENTS");

        btnAfegir.setText("Afegir Clients");
        btnAfegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfegirActionPerformed(evt);
            }
        });

        btnTornar.setText("Tornar");
        btnTornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTornarActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(lstMostraClients);

        etLlista.setText("Llista de clients:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(etLlista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addGap(83, 83, 83))
            .addGroup(layout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addComponent(btnAfegir)
                .addGap(172, 172, 172)
                .addComponent(btnTornar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(245, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(60, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(etLlista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAfegir)
                    .addComponent(btnTornar))
                .addGap(98, 98, 98))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * Mètode per a donar funcionalitat al button per tornar a AppMercatUB
     * @param evt Permet assignar un event
     */
    private void btnTornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTornarActionPerformed
        // TODO add your handling code here:
        AppMercatUB app = new AppMercatUB();
        this.dispose();


    }//GEN-LAST:event_btnTornarActionPerformed
/**
     * Mètode per a donar funcionalitat al button Afegir Client
     * @param evt Permet assignar un event
     */
    private void btnAfegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfegirActionPerformed
        // TODO add your handling code here:
        FrmAfegirClient afegir = new FrmAfegirClient(this,true,controlador);
        this.setVisible(false);
        afegir.pack();
        afegir.setVisible(true);
       
    }//GEN-LAST:event_btnAfegirActionPerformed
    
     /**
     * Mètode per a omplir l'Array de Clients que posteriorment voldrem mostrar per pantalla
     * a partir del mètode toString
     */
    private void omplirModel() {
        DefaultListModel model = new DefaultListModel();
        model.clear();
        //try{
            List<String> s = controlador.recuperaClients();
            for(String item : s){
                model.addElement(item);
                
            }
            lstMostraClients.setModel(model);
            
            
      
    /*}catch(MercatException e){
        JOptionPane.showMessageDialog(this, e.getMessage(), "warning", JOptionPane.WARNING_MESSAGE);
        
    }*/

    }

 
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAfegir;
    private javax.swing.JButton btnTornar;
    private javax.swing.JLabel etLlista;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstMostraClients;
    // End of variables declaration//GEN-END:variables
}
