/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ub.info.prog2.DeCaraltOscarSeguraPau.vista;
import java.util.List;
import javax.swing.DefaultListModel;
import prog2.controlador.Controlador;
/**
 *
 * @author Pau Segura
 */
public class FrmGestioArticles extends javax.swing.JFrame {
   private final Controlador controlador;
    /**
     * Creates new form FrmGestioArticles
     * @param controlador Permet accedir als mètodes de la classe controlador
     */
    public FrmGestioArticles(Controlador controlador) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.controlador = controlador;
        omplirModel();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnArticle = new javax.swing.JButton();
        btnTornar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstMostraArticles = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GESTIÓ ARTICLES");

        btnArticle.setText("Afegir Article");
        btnArticle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArticleActionPerformed(evt);
            }
        });

        btnTornar.setText("Tornar");
        btnTornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTornarActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(lstMostraArticles);

        jLabel1.setText("Llista d'articles:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnArticle)
                        .addGap(210, 210, 210)
                        .addComponent(btnTornar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(217, 217, 217))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel1)))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnArticle)
                    .addComponent(btnTornar))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 /**
     * Mètode per a donar funcionalitat al button Afegir Article
     * @param evt Permet assignar un event
     */
    private void btnArticleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArticleActionPerformed
        // TODO add your handling code here:
        FrmAfegirArticle article = new FrmAfegirArticle(this,true,controlador);
        this.setVisible(false);
        article.setVisible(true);
        omplirModel();
        
    }//GEN-LAST:event_btnArticleActionPerformed
/**
     * Mètode per a donar funcionalitat al button per tornar a AppMercatUB
     * @param evt Permet assignar un event
     */
    private void btnTornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTornarActionPerformed
        // TODO add your handling code here:
        AppMercatUB ub = new AppMercatUB();        
        this.dispose();
      
        
    }//GEN-LAST:event_btnTornarActionPerformed
    
     /**
     * Mètode per a omplir l'Array d'Articles que posteriorment voldrem mostrar per pantalla
     * a partir del mètode toString
     */
    private void omplirModel() {
        DefaultListModel model = new DefaultListModel();
        model.clear();
        //try{
            List<String> s = controlador.recuperaArticles();
            for(String item : s){
                model.addElement(item);
                
            }
            lstMostraArticles.setModel(model);
            
            
      
    /*}catch(MercatException e){
        JOptionPane.showMessageDialog(this, e.getMessage(), "warning", JOptionPane.WARNING_MESSAGE);
        
    }*/

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArticle;
    private javax.swing.JButton btnTornar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstMostraArticles;
    // End of variables declaration//GEN-END:variables
}
