/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ub.info.prog2.DeCaraltOscarSeguraPau.vista;

import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import prog2.controlador.Controlador;

/**
 *
 * @author Pau Segura
 */
public class FrmGestioComandes extends javax.swing.JFrame {

    private final Controlador controlador;

    /**
     * Creates new form FrmGestioComandes
     * @param controlador Permet accedir als mètodes de la classe controlador
     */
    public FrmGestioComandes(Controlador controlador) {
        initComponents();
        this.controlador = controlador;
        this.setLocationRelativeTo(null);
        omplirModel();
        btnEliminarComanda.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAfegirComanda = new javax.swing.JButton();
        btnEliminarComanda = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstComandes = new javax.swing.JList<>();
        etComandes = new javax.swing.JLabel();
        btnTornar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GESTIÓ COMANDES");

        btnAfegirComanda.setText("Afegir Comanda");
        btnAfegirComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfegirComandaActionPerformed(evt);
            }
        });

        btnEliminarComanda.setText("Eliminar Comanda");
        btnEliminarComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarComandaActionPerformed(evt);
            }
        });

        lstComandes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstComandesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstComandes);

        etComandes.setText("Comandes:");

        btnTornar.setText("Tornar");
        btnTornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTornarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etComandes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnAfegirComanda)
                        .addGap(98, 98, 98)
                        .addComponent(btnEliminarComanda)
                        .addGap(94, 94, 94)
                        .addComponent(btnTornar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(etComandes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(87, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarComanda)
                    .addComponent(btnAfegirComanda)
                    .addComponent(btnTornar))
                .addGap(91, 91, 91))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * Mètode per a donar funcionalitat al button per tornar a AppMercatUB
     * @param evt Permet assignar un event
     */
    private void btnTornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTornarActionPerformed
        // TODO add your handling code here:
        AppMercatUB app = new AppMercatUB();
        this.dispose();
    }//GEN-LAST:event_btnTornarActionPerformed
/**
     * Mètode per a donar funcionalitat al button per afegir Comandes
     * @param evt Permet assignar un event
     */
    private void btnAfegirComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfegirComandaActionPerformed
        // TODO add your handling code here:
        FrmAfegirComandes afegir = new FrmAfegirComandes(this, true, controlador);
        this.setVisible(false);
        afegir.pack();
        afegir.setVisible(true);
    }//GEN-LAST:event_btnAfegirComandaActionPerformed

    /**
     * Mètode per a donar funcionalitat al button per esborrar Comandes
     * @param evt Permet assignar un event
     */
    private void btnEliminarComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarComandaActionPerformed
        // TODO add your handling code here:
        int i = -1;
        for (String item : lstComandes.getSelectedValuesList()) {
            
                String elementSeleccionat = item;
                i +=1;
            try {
                controlador.esborrarComandes(i);
            } catch (MercatException ex) {
               JOptionPane.showMessageDialog(this, "Aquesta comanda no s'ha pogut eliminar perquè ja ha estat enviada ","ERROR: MERCAT EXCEPTION", JOptionPane.ERROR_MESSAGE);
            }
            
        }
        omplirModel();

    
        
        
        
        
        
    }//GEN-LAST:event_btnEliminarComandaActionPerformed
/**
     * Mètode per a activar el button per esborrar Comandes
     * @param evt Permet assignar un event
     */
    private void lstComandesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstComandesValueChanged
        // TODO add your handling code here:
        
        btnEliminarComanda.setEnabled(!lstComandes.isSelectionEmpty());
        
    }//GEN-LAST:event_lstComandesValueChanged
    /**
     * Mètode per a omplir l'Array de comandes que posteriorment voldrem mostrar per pantalla
     * a partir del mètode toString
     */
    private void omplirModel() {
        DefaultListModel model = new DefaultListModel();
        model.clear();
       
        List<String> s = controlador.recuperaComandes();
        for (String item : s) {
            model.addElement(item);

        }
        lstComandes.setModel(model);

        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAfegirComanda;
    private javax.swing.JButton btnEliminarComanda;
    private javax.swing.JButton btnTornar;
    private javax.swing.JLabel etComandes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstComandes;
    // End of variables declaration//GEN-END:variables
}
